version: 0.1
phases:
  install:
    commands:
      - sam package --template-file template.yaml --output-template-file output-template.yaml --s3-bucket sk-03042020
artifacts:
  type: zip
  files:
    - template.yaml
    - output-template.yaml