AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  profile-serverless

  Sample SAM Template for profile-serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ProfileLoaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ProfileLoaderFunction
      Description: A lambda funtion to load the profile from json
      CodeUri: profile_loader
      Handler: profileloader.lambda_handler
      Runtime: python3.7
      Events:
        ProfileLoaderApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /loadProfile
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProfileLoaderApi:
    Description: "API Gateway endpoint URL for Prod stage for ProfileLoaderFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/loadProfile/"
  ProfileLoaderFunction:
    Description: "ProfileLoaderFunction ARN"
    Value: !GetAtt ProfileLoaderFunction.Arn
  ProfileLoaderFunctionIamRole:
    Description: "Implicit IAM Role created for ProfileLoaderFunction"
    Value: !GetAtt ProfileLoaderFunctionRole.Arn
